apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/kubedata
    server: 192.168.1.6
  persistentVolumeReclaimPolicy: Delete

  
